set_property IOSTANDARD LVCMOS33 [get_ports EXCLK]
set_property PACKAGE_PIN J15 [get_ports Cir_reset]
set_property IOSTANDARD LVCMOS33 [get_ports Cir_reset]
set_property PACKAGE_PIN N18 [get_ports EXCLK]
set_property PACKAGE_PIN J20 [get_ports clk_reset]
set_property IOSTANDARD LVCMOS33 [get_ports clk_reset]
set_property PACKAGE_PIN L20 [get_ports MOD_SEL_KEY]
set_property IOSTANDARD LVCMOS33 [get_ports MOD_SEL_KEY]


set_property IOSTANDARD LVCMOS33 [get_ports ADRF_EN]
set_property PACKAGE_PIN R14 [get_ports ADRF_EN]
set_property PACKAGE_PIN M15 [get_ports DA_PLL_LOCK]


set_property PACKAGE_PIN L16 [get_ports DA_CS_OUT]
set_property PACKAGE_PIN L17 [get_ports DA_SPI_OUT]
set_property PACKAGE_PIN P14 [get_ports ADRF_CS]
set_property PACKAGE_PIN T10 [get_ports ADRF_SPI_OUT]
set_property PACKAGE_PIN V13 [get_ports DA_EN_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports ADRF_SPI_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports DA_EN_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports ADRF_CS]
set_property IOSTANDARD LVCMOS33 [get_ports DA_CS_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports DA_SPI_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports DA_PLL_LOCK]
set_property IOSTANDARD LVCMOS33 [get_ports ADRF_SCLK_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports DA_SCLK_OUT]
set_property PACKAGE_PIN T11 [get_ports ADRF_SCLK_OUT]
set_property PACKAGE_PIN M19 [get_ports DA_SCLK_OUT]


set_property IOSTANDARD LVCMOS33 [get_ports DA_RESET]
set_property PACKAGE_PIN M18 [get_ports DA_RESET]




set_property DRIVE 12 [get_ports DA_SCLK]


set_property IOSTANDARD LVCMOS33 [get_ports DA_DATA_CLK]
set_property PACKAGE_PIN N20 [get_ports DA_DATA_CLK]

set_property IOSTANDARD LVCMOS33 [get_ports DA_SPI_IN]
set_property PACKAGE_PIN M14 [get_ports DA_SPI_IN]

set_property PACKAGE_PIN J18 [get_ports lock]
set_property IOSTANDARD LVCMOS33 [get_ports lock]
set_property PACKAGE_PIN R18 [get_ports {Idata[0]}]
set_property PACKAGE_PIN T17 [get_ports {Idata[1]}]
set_property PACKAGE_PIN P15 [get_ports {Idata[2]}]
set_property PACKAGE_PIN P16 [get_ports {Idata[3]}]
set_property PACKAGE_PIN V15 [get_ports {Idata[4]}]
set_property PACKAGE_PIN W15 [get_ports {Idata[5]}]
set_property PACKAGE_PIN T12 [get_ports {Idata[6]}]
set_property PACKAGE_PIN U12 [get_ports {Idata[7]}]
set_property PACKAGE_PIN V12 [get_ports {Idata[8]}]
set_property PACKAGE_PIN W13 [get_ports {Idata[9]}]
set_property PACKAGE_PIN T14 [get_ports {Idata[10]}]
set_property PACKAGE_PIN T15 [get_ports {Idata[11]}]
set_property PACKAGE_PIN R16 [get_ports {Idata[12]}]
set_property PACKAGE_PIN R17 [get_ports {Idata[13]}]

set_property PACKAGE_PIN P18 [get_ports {Idata[14]}]
set_property PACKAGE_PIN N17 [get_ports {Idata[15]}]
set_property PACKAGE_PIN V16 [get_ports {Qdata[0]}]
set_property PACKAGE_PIN W16 [get_ports {Qdata[1]}]

set_property PACKAGE_PIN W18 [get_ports {Qdata[2]}]
set_property PACKAGE_PIN W19 [get_ports {Qdata[3]}]
set_property PACKAGE_PIN Y19 [get_ports {Qdata[5]}]
set_property PACKAGE_PIN U14 [get_ports {Qdata[8]}]
set_property PACKAGE_PIN U15 [get_ports {Qdata[9]}]
set_property PACKAGE_PIN T20 [get_ports {Qdata[10]}]
set_property PACKAGE_PIN U20 [get_ports {Qdata[11]}]
set_property PACKAGE_PIN T16 [get_ports {Qdata[12]}]
set_property PACKAGE_PIN U17 [get_ports {Qdata[13]}]
set_property PACKAGE_PIN Y16 [get_ports {Qdata[14]}]
set_property PACKAGE_PIN Y17 [get_ports {Qdata[15]}]
set_property PACKAGE_PIN Y18 [get_ports {Qdata[4]}]
set_property PACKAGE_PIN V20 [get_ports {Qdata[6]}]
set_property PACKAGE_PIN W20 [get_ports {Qdata[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Idata[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Idata[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Idata[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Idata[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Idata[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Idata[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Idata[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Idata[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Idata[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Idata[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Idata[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Idata[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Idata[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Idata[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Idata[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Idata[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qdata[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qdata[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qdata[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qdata[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qdata[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qdata[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qdata[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qdata[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qdata[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qdata[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qdata[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qdata[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qdata[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qdata[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qdata[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qdata[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {TQPM[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TQPM[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TQPM[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TQPM[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TQPM[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TQPM[0]}]
set_property PACKAGE_PIN E17 [get_ports {TQPM[0]}]
set_property PACKAGE_PIN D18 [get_ports {TQPM[1]}]
set_property PACKAGE_PIN D19 [get_ports {TQPM[2]}]
set_property PACKAGE_PIN D20 [get_ports {TQPM[3]}]
set_property PACKAGE_PIN K14 [get_ports {TQPM[4]}]
set_property PACKAGE_PIN J14 [get_ports {TQPM[5]}]

create_clock -period 10.000 -name VIRTUAL_clk_out5_clk_wiz_0 -waveform {0.000 5.00}
create_clock -period 2.500 -name VIRTUAL_clk_out2_clk_wiz_0 -waveform {0.000 1.250}
create_clock -period 80.000 -name VIRTUAL_clk_out3_clk_wiz_0 -waveform {0.000 40.000}
create_clock -period 80.000 -name VIRTUAL_clk_out4_clk_wiz_0 -waveform {0.000 40.000}
# set_output_delay -clock [get_clocks VIRTUAL_clk_out5_clk_wiz_0] -min -add_delay -4.325 [get_ports {Idata[*]}]
# set_output_delay -clock [get_clocks VIRTUAL_clk_out5_clk_wiz_0] -max -add_delay -1.199 [get_ports {Idata[*]}]
# set_output_delay -clock [get_clocks VIRTUAL_clk_out5_clk_wiz_0] -min -add_delay -4.325 [get_ports {Qdata[*]}]
# set_output_delay -clock [get_clocks VIRTUAL_clk_out5_clk_wiz_0] -max -add_delay -1.199 [get_ports {Qdata[*]}]
set_output_delay -clock [get_clocks VIRTUAL_clk_out3_clk_wiz_0] -min -add_delay -9.549 [get_ports ADRF_CS]
set_output_delay -clock [get_clocks VIRTUAL_clk_out3_clk_wiz_0] -max -add_delay 10.451 [get_ports ADRF_CS]
set_output_delay -clock [get_clocks VIRTUAL_clk_out3_clk_wiz_0] -min -add_delay -7.514 [get_ports ADRF_EN]
set_output_delay -clock [get_clocks VIRTUAL_clk_out3_clk_wiz_0] -max -add_delay 8.486 [get_ports ADRF_EN]
set_output_delay -clock [get_clocks VIRTUAL_clk_out3_clk_wiz_0] -min -add_delay -7.561 [get_ports ADRF_SPI_OUT]
set_output_delay -clock [get_clocks VIRTUAL_clk_out3_clk_wiz_0] -max -add_delay 8.439 [get_ports ADRF_SPI_OUT]
set_output_delay -clock [get_clocks VIRTUAL_clk_out4_clk_wiz_0] -min -add_delay 0.292 [get_ports DA_CS_OUT]
set_output_delay -clock [get_clocks VIRTUAL_clk_out4_clk_wiz_0] -max -add_delay 3.292 [get_ports DA_CS_OUT]
set_output_delay -clock [get_clocks VIRTUAL_clk_out4_clk_wiz_0] -min -add_delay 0.310 [get_ports DA_EN_OUT]
set_output_delay -clock [get_clocks VIRTUAL_clk_out4_clk_wiz_0] -max -add_delay 3.310 [get_ports DA_EN_OUT]
set_output_delay -clock [get_clocks VIRTUAL_clk_out4_clk_wiz_0] -min -add_delay 0.292 [get_ports DA_SPI_OUT]
set_output_delay -clock [get_clocks VIRTUAL_clk_out4_clk_wiz_0] -max -add_delay 3.092 [get_ports DA_SPI_OUT]

set_property PULLUP true [get_ports {TQPM[0]}]
set_property PULLUP true [get_ports {TQPM[1]}]
set_property PULLUP true [get_ports {TQPM[2]}]
set_property PULLUP true [get_ports {TQPM[3]}]
set_property PULLUP true [get_ports {TQPM[4]}]
set_property PULLUP true [get_ports {TQPM[5]}]
set_property PULLUP true [get_ports DA_CS_OUT]
set_property PULLUP true [get_ports DA_SPI_OUT]
set_property PULLUP true [get_ports DA_SCLK_OUT]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets MOD_SEL_KEY]

